#ifndef GRAMMAR_H
#define GRAMMAR_H
#include "parserDef.h"
struct ruleRightSideElement _otherFunctions = {false, false, .symbol.nonTerminal = NT_OtherFunctions};
struct ruleRightSideElement _mainFunction = {false, false, .symbol.nonTerminal = NT_MainFunction};
RuleRightSideElement _rhs0[] = {&_otherFunctions, &_mainFunction, };
struct rule _rule0 = {.lhs = NT_Program, .rhs = _rhs0, .rhsLength = 2};
struct ruleRightSideElement _tk_main = {false, true, .symbol.terminal = TK_MAIN};
struct ruleRightSideElement _stmts = {false, false, .symbol.nonTerminal = NT_Stmts};
struct ruleRightSideElement _tk_end = {false, true, .symbol.terminal = TK_END};
RuleRightSideElement _rhs1[] = {&_tk_main, &_stmts, &_tk_end, };
struct rule _rule1 = {.lhs = NT_MainFunction, .rhs = _rhs1, .rhsLength = 3};
struct ruleRightSideElement _function = {false, false, .symbol.nonTerminal = NT_Function};
RuleRightSideElement _rhs2[] = {&_function, &_otherFunctions, };
struct rule _rule2 = {.lhs = NT_OtherFunctions, .rhs = _rhs2, .rhsLength = 2};
struct ruleRightSideElement _eps = {true, true, .symbol.terminal = TK_ID};
RuleRightSideElement _rhs3[] = {&_eps, };
struct rule _rule3 = {.lhs = NT_OtherFunctions, .rhs = _rhs3, .rhsLength = 1};
struct ruleRightSideElement _tk_funid = {false, true, .symbol.terminal = TK_FUNID};
struct ruleRightSideElement _inputPar = {false, false, .symbol.nonTerminal = NT_InputPar};
struct ruleRightSideElement _outputPar = {false, false, .symbol.nonTerminal = NT_OutputPar};
struct ruleRightSideElement _tk_sem = {false, true, .symbol.terminal = TK_SEM};
RuleRightSideElement _rhs4[] = {&_tk_funid, &_inputPar, &_outputPar, &_tk_sem, &_stmts, &_tk_end, };
struct rule _rule4 = {.lhs = NT_Function, .rhs = _rhs4, .rhsLength = 6};
struct ruleRightSideElement _tk_input = {false, true, .symbol.terminal = TK_INPUT};
struct ruleRightSideElement _tk_parameter = {false, true, .symbol.terminal = TK_PARAMETER};
struct ruleRightSideElement _tk_list = {false, true, .symbol.terminal = TK_LIST};
struct ruleRightSideElement _tk_sql = {false, true, .symbol.terminal = TK_SQL};
struct ruleRightSideElement _parameterList = {false, false, .symbol.nonTerminal = NT_ParameterList};
struct ruleRightSideElement _tk_sqr = {false, true, .symbol.terminal = TK_SQR};
RuleRightSideElement _rhs5[] = {&_tk_input, &_tk_parameter, &_tk_list, &_tk_sql, &_parameterList, &_tk_sqr, };
struct rule _rule5 = {.lhs = NT_InputPar, .rhs = _rhs5, .rhsLength = 6};
RuleRightSideElement _rhs6[] = {&_tk_input, &_tk_parameter, &_tk_list, &_tk_sql, &_parameterList, &_tk_sqr, };
struct rule _rule6 = {.lhs = NT_OutputPar, .rhs = _rhs6, .rhsLength = 6};
RuleRightSideElement _rhs7[] = {&_eps, };
struct rule _rule7 = {.lhs = NT_OutputPar, .rhs = _rhs7, .rhsLength = 1};
struct ruleRightSideElement _dataType = {false, false, .symbol.nonTerminal = NT_DataType};
struct ruleRightSideElement _tk_id = {false, true, .symbol.terminal = TK_ID};
struct ruleRightSideElement _remainingList = {false, false, .symbol.nonTerminal = NT_RemainingList};
RuleRightSideElement _rhs8[] = {&_dataType, &_tk_id, &_remainingList, };
struct rule _rule8 = {.lhs = NT_ParameterList, .rhs = _rhs8, .rhsLength = 3};
struct ruleRightSideElement _primitiveDatatype = {false, false, .symbol.nonTerminal = NT_PrimitiveDatatype};
RuleRightSideElement _rhs9[] = {&_primitiveDatatype, };
struct rule _rule9 = {.lhs = NT_DataType, .rhs = _rhs9, .rhsLength = 1};
struct ruleRightSideElement _constructedDatatype = {false, false, .symbol.nonTerminal = NT_ConstructedDatatype};
RuleRightSideElement _rhs10[] = {&_constructedDatatype, };
struct rule _rule10 = {.lhs = NT_DataType, .rhs = _rhs10, .rhsLength = 1};
struct ruleRightSideElement _tk_int = {false, true, .symbol.terminal = TK_INT};
RuleRightSideElement _rhs11[] = {&_tk_int, };
struct rule _rule11 = {.lhs = NT_PrimitiveDatatype, .rhs = _rhs11, .rhsLength = 1};
struct ruleRightSideElement _tk_real = {false, true, .symbol.terminal = TK_REAL};
RuleRightSideElement _rhs12[] = {&_tk_real, };
struct rule _rule12 = {.lhs = NT_PrimitiveDatatype, .rhs = _rhs12, .rhsLength = 1};
struct ruleRightSideElement _tk_record = {false, true, .symbol.terminal = TK_RECORD};
struct ruleRightSideElement _tk_ruid = {false, true, .symbol.terminal = TK_RUID};
RuleRightSideElement _rhs13[] = {&_tk_record, &_tk_ruid, };
struct rule _rule13 = {.lhs = NT_ConstructedDatatype, .rhs = _rhs13, .rhsLength = 2};
struct ruleRightSideElement _tk_union = {false, true, .symbol.terminal = TK_UNION};
RuleRightSideElement _rhs14[] = {&_tk_union, &_tk_ruid, };
struct rule _rule14 = {.lhs = NT_ConstructedDatatype, .rhs = _rhs14, .rhsLength = 2};
RuleRightSideElement _rhs15[] = {&_tk_ruid, };
struct rule _rule15 = {.lhs = NT_ConstructedDatatype, .rhs = _rhs15, .rhsLength = 1};
struct ruleRightSideElement _tk_comma = {false, true, .symbol.terminal = TK_COMMA};
RuleRightSideElement _rhs16[] = {&_tk_comma, &_parameterList, };
struct rule _rule16 = {.lhs = NT_RemainingList, .rhs = _rhs16, .rhsLength = 2};
RuleRightSideElement _rhs17[] = {&_eps, };
struct rule _rule17 = {.lhs = NT_RemainingList, .rhs = _rhs17, .rhsLength = 1};
struct ruleRightSideElement _typeDefinitions = {false, false, .symbol.nonTerminal = NT_TypeDefinitions};
struct ruleRightSideElement _declaration = {false, false, .symbol.nonTerminal = NT_Declaration};
struct ruleRightSideElement _otherStmts = {false, false, .symbol.nonTerminal = NT_OtherStmts};
struct ruleRightSideElement _returnStmt = {false, false, .symbol.nonTerminal = NT_ReturnStmt};
RuleRightSideElement _rhs18[] = {&_typeDefinitions, &_declaration, &_otherStmts, &_returnStmt, };
struct rule _rule18 = {.lhs = NT_Stmts, .rhs = _rhs18, .rhsLength = 4};
struct ruleRightSideElement _actualOrRedefined = {false, false, .symbol.nonTerminal = NT_ActualOrRedefined};
RuleRightSideElement _rhs19[] = {&_actualOrRedefined, &_typeDefinitions, };
struct rule _rule19 = {.lhs = NT_TypeDefinitions, .rhs = _rhs19, .rhsLength = 2};
RuleRightSideElement _rhs20[] = {&_eps, };
struct rule _rule20 = {.lhs = NT_TypeDefinitions, .rhs = _rhs20, .rhsLength = 1};
struct ruleRightSideElement _typeDefinition = {false, false, .symbol.nonTerminal = NT_TypeDefinition};
RuleRightSideElement _rhs21[] = {&_typeDefinition, };
struct rule _rule21 = {.lhs = NT_ActualOrRedefined, .rhs = _rhs21, .rhsLength = 1};
struct ruleRightSideElement _definetypeStmt = {false, false, .symbol.nonTerminal = NT_DefinetypeStmt};
RuleRightSideElement _rhs22[] = {&_definetypeStmt, };
struct rule _rule22 = {.lhs = NT_ActualOrRedefined, .rhs = _rhs22, .rhsLength = 1};
struct ruleRightSideElement _fieldDefinitions = {false, false, .symbol.nonTerminal = NT_FieldDefinitions};
struct ruleRightSideElement _tk_endrecord = {false, true, .symbol.terminal = TK_ENDRECORD};
RuleRightSideElement _rhs23[] = {&_tk_record, &_tk_ruid, &_fieldDefinitions, &_tk_endrecord, };
struct rule _rule23 = {.lhs = NT_TypeDefinition, .rhs = _rhs23, .rhsLength = 4};
struct ruleRightSideElement _tk_endunion = {false, true, .symbol.terminal = TK_ENDUNION};
RuleRightSideElement _rhs24[] = {&_tk_union, &_tk_ruid, &_fieldDefinitions, &_tk_endunion, };
struct rule _rule24 = {.lhs = NT_TypeDefinition, .rhs = _rhs24, .rhsLength = 4};
struct ruleRightSideElement _fieldDefinition = {false, false, .symbol.nonTerminal = NT_FieldDefinition};
struct ruleRightSideElement _moreFields = {false, false, .symbol.nonTerminal = NT_MoreFields};
RuleRightSideElement _rhs25[] = {&_fieldDefinition, &_fieldDefinition, &_moreFields, };
struct rule _rule25 = {.lhs = NT_FieldDefinitions, .rhs = _rhs25, .rhsLength = 3};
struct ruleRightSideElement _tk_type = {false, true, .symbol.terminal = TK_TYPE};
struct ruleRightSideElement _tk_colon = {false, true, .symbol.terminal = TK_COLON};
struct ruleRightSideElement _tk_fieldid = {false, true, .symbol.terminal = TK_FIELDID};
RuleRightSideElement _rhs26[] = {&_tk_type, &_dataType, &_tk_colon, &_tk_fieldid, &_tk_sem, };
struct rule _rule26 = {.lhs = NT_FieldDefinition, .rhs = _rhs26, .rhsLength = 5};
RuleRightSideElement _rhs27[] = {&_fieldDefinition, &_moreFields, };
struct rule _rule27 = {.lhs = NT_MoreFields, .rhs = _rhs27, .rhsLength = 2};
RuleRightSideElement _rhs28[] = {&_eps, };
struct rule _rule28 = {.lhs = NT_MoreFields, .rhs = _rhs28, .rhsLength = 1};
struct ruleRightSideElement _declarations = {false, false, .symbol.nonTerminal = NT_Declarations};
RuleRightSideElement _rhs29[] = {&_declaration, &_declarations, };
struct rule _rule29 = {.lhs = NT_Declarations, .rhs = _rhs29, .rhsLength = 2};
RuleRightSideElement _rhs30[] = {&_eps, };
struct rule _rule30 = {.lhs = NT_Declarations, .rhs = _rhs30, .rhsLength = 1};
struct ruleRightSideElement _globalOrNot = {false, false, .symbol.nonTerminal = NT_GlobalOrNot};
RuleRightSideElement _rhs31[] = {&_tk_type, &_dataType, &_tk_colon, &_tk_id, &_globalOrNot, &_tk_sem, };
struct rule _rule31 = {.lhs = NT_Declaration, .rhs = _rhs31, .rhsLength = 6};
struct ruleRightSideElement _tk_global = {false, true, .symbol.terminal = TK_GLOBAL};
RuleRightSideElement _rhs32[] = {&_tk_colon, &_tk_global, };
struct rule _rule32 = {.lhs = NT_GlobalOrNot, .rhs = _rhs32, .rhsLength = 2};
RuleRightSideElement _rhs33[] = {&_eps, };
struct rule _rule33 = {.lhs = NT_GlobalOrNot, .rhs = _rhs33, .rhsLength = 1};
struct ruleRightSideElement _stmt = {false, false, .symbol.nonTerminal = NT_Stmt};
RuleRightSideElement _rhs34[] = {&_stmt, &_otherStmts, };
struct rule _rule34 = {.lhs = NT_OtherStmts, .rhs = _rhs34, .rhsLength = 2};
RuleRightSideElement _rhs35[] = {&_eps, };
struct rule _rule35 = {.lhs = NT_OtherStmts, .rhs = _rhs35, .rhsLength = 1};
struct ruleRightSideElement _assignmentStmt = {false, false, .symbol.nonTerminal = NT_AssignmentStmt};
RuleRightSideElement _rhs36[] = {&_assignmentStmt, };
struct rule _rule36 = {.lhs = NT_Stmt, .rhs = _rhs36, .rhsLength = 1};
struct ruleRightSideElement _iterativeStmt = {false, false, .symbol.nonTerminal = NT_IterativeStmt};
RuleRightSideElement _rhs37[] = {&_iterativeStmt, };
struct rule _rule37 = {.lhs = NT_Stmt, .rhs = _rhs37, .rhsLength = 1};
struct ruleRightSideElement _conditionalStmt = {false, false, .symbol.nonTerminal = NT_ConditionalStmt};
RuleRightSideElement _rhs38[] = {&_conditionalStmt, };
struct rule _rule38 = {.lhs = NT_Stmt, .rhs = _rhs38, .rhsLength = 1};
struct ruleRightSideElement _ioStmt = {false, false, .symbol.nonTerminal = NT_IoStmt};
RuleRightSideElement _rhs39[] = {&_ioStmt, };
struct rule _rule39 = {.lhs = NT_Stmt, .rhs = _rhs39, .rhsLength = 1};
struct ruleRightSideElement _funCallStmt = {false, false, .symbol.nonTerminal = NT_FunCallStmt};
RuleRightSideElement _rhs40[] = {&_funCallStmt, };
struct rule _rule40 = {.lhs = NT_Stmt, .rhs = _rhs40, .rhsLength = 1};
struct ruleRightSideElement _singleOrRecId = {false, false, .symbol.nonTerminal = NT_SingleOrRecId};
struct ruleRightSideElement _tk_assignop = {false, true, .symbol.terminal = TK_ASSIGNOP};
struct ruleRightSideElement _arithmeticExpression = {false, false, .symbol.nonTerminal = NT_ArithmeticExpression};
RuleRightSideElement _rhs41[] = {&_singleOrRecId, &_tk_assignop, &_arithmeticExpression, &_tk_sem, };
struct rule _rule41 = {.lhs = NT_AssignmentStmt, .rhs = _rhs41, .rhsLength = 4};
struct ruleRightSideElement _optionSingleConstructed = {false, false, .symbol.nonTerminal = NT_OptionSingleConstructed};
RuleRightSideElement _rhs42[] = {&_tk_id, &_optionSingleConstructed, };
struct rule _rule42 = {.lhs = NT_SingleOrRecId, .rhs = _rhs42, .rhsLength = 2};
RuleRightSideElement _rhs43[] = {&_eps, };
struct rule _rule43 = {.lhs = NT_OptionSingleConstructed, .rhs = _rhs43, .rhsLength = 1};
struct ruleRightSideElement _oneExpansion = {false, false, .symbol.nonTerminal = NT_OneExpansion};
struct ruleRightSideElement _moreExpansions = {false, false, .symbol.nonTerminal = NT_MoreExpansions};
RuleRightSideElement _rhs44[] = {&_oneExpansion, &_moreExpansions, };
struct rule _rule44 = {.lhs = NT_OptionSingleConstructed, .rhs = _rhs44, .rhsLength = 2};
struct ruleRightSideElement _tk_dot = {false, true, .symbol.terminal = TK_DOT};
RuleRightSideElement _rhs45[] = {&_tk_dot, &_tk_fieldid, };
struct rule _rule45 = {.lhs = NT_OneExpansion, .rhs = _rhs45, .rhsLength = 2};
RuleRightSideElement _rhs46[] = {&_oneExpansion, &_moreExpansions, };
struct rule _rule46 = {.lhs = NT_MoreExpansions, .rhs = _rhs46, .rhsLength = 2};
RuleRightSideElement _rhs47[] = {&_eps, };
struct rule _rule47 = {.lhs = NT_MoreExpansions, .rhs = _rhs47, .rhsLength = 1};
struct ruleRightSideElement _outputParameters = {false, false, .symbol.nonTerminal = NT_OutputParameters};
struct ruleRightSideElement _tk_call = {false, true, .symbol.terminal = TK_CALL};
struct ruleRightSideElement _tk_with = {false, true, .symbol.terminal = TK_WITH};
struct ruleRightSideElement _tk_parameters = {false, true, .symbol.terminal = TK_PARAMETERS};
struct ruleRightSideElement _inputParameters = {false, false, .symbol.nonTerminal = NT_InputParameters};
RuleRightSideElement _rhs48[] = {&_outputParameters, &_tk_call, &_tk_funid, &_tk_with, &_tk_parameters, &_inputParameters, &_tk_sem, };
struct rule _rule48 = {.lhs = NT_FunCallStmt, .rhs = _rhs48, .rhsLength = 7};
struct ruleRightSideElement _idList = {false, false, .symbol.nonTerminal = NT_IdList};
RuleRightSideElement _rhs49[] = {&_tk_sql, &_idList, &_tk_sqr, &_tk_assignop, };
struct rule _rule49 = {.lhs = NT_OutputParameters, .rhs = _rhs49, .rhsLength = 4};
RuleRightSideElement _rhs50[] = {&_eps, };
struct rule _rule50 = {.lhs = NT_OutputParameters, .rhs = _rhs50, .rhsLength = 1};
RuleRightSideElement _rhs51[] = {&_tk_sql, &_idList, &_tk_sqr, };
struct rule _rule51 = {.lhs = NT_InputParameters, .rhs = _rhs51, .rhsLength = 3};
struct ruleRightSideElement _tk_while = {false, true, .symbol.terminal = TK_WHILE};
struct ruleRightSideElement _tk_op = {false, true, .symbol.terminal = TK_OP};
struct ruleRightSideElement _booleanExpression = {false, false, .symbol.nonTerminal = NT_BooleanExpression};
struct ruleRightSideElement _tk_cl = {false, true, .symbol.terminal = TK_CL};
struct ruleRightSideElement _tk_endwhile = {false, true, .symbol.terminal = TK_ENDWHILE};
RuleRightSideElement _rhs52[] = {&_tk_while, &_tk_op, &_booleanExpression, &_tk_cl, &_stmt, &_otherStmts, &_tk_endwhile, };
struct rule _rule52 = {.lhs = NT_IterativeStmt, .rhs = _rhs52, .rhsLength = 7};
struct ruleRightSideElement _tk_if = {false, true, .symbol.terminal = TK_IF};
struct ruleRightSideElement _tk_then = {false, true, .symbol.terminal = TK_THEN};
struct ruleRightSideElement _elsePart = {false, false, .symbol.nonTerminal = NT_ElsePart};
struct ruleRightSideElement _tk_endif = {false, true, .symbol.terminal = TK_ENDIF};
RuleRightSideElement _rhs53[] = {&_tk_if, &_tk_op, &_booleanExpression, &_tk_cl, &_tk_then, &_stmt, &_otherStmts, &_elsePart, &_tk_endif, };
struct rule _rule53 = {.lhs = NT_ConditionalStmt, .rhs = _rhs53, .rhsLength = 9};
struct ruleRightSideElement _tk_else = {false, true, .symbol.terminal = TK_ELSE};
RuleRightSideElement _rhs54[] = {&_tk_else, &_stmt, &_otherStmts, };
struct rule _rule54 = {.lhs = NT_ElsePart, .rhs = _rhs54, .rhsLength = 3};
RuleRightSideElement _rhs55[] = {&_eps, };
struct rule _rule55 = {.lhs = NT_ElsePart, .rhs = _rhs55, .rhsLength = 1};
struct ruleRightSideElement _tk_read = {false, true, .symbol.terminal = TK_READ};
struct ruleRightSideElement _var = {false, false, .symbol.nonTerminal = NT_Var};
RuleRightSideElement _rhs56[] = {&_tk_read, &_tk_op, &_var, &_tk_cl, &_tk_sem, };
struct rule _rule56 = {.lhs = NT_IoStmt, .rhs = _rhs56, .rhsLength = 5};
struct ruleRightSideElement _tk_write = {false, true, .symbol.terminal = TK_WRITE};
RuleRightSideElement _rhs57[] = {&_tk_write, &_tk_op, &_var, &_tk_cl, &_tk_sem, };
struct rule _rule57 = {.lhs = NT_IoStmt, .rhs = _rhs57, .rhsLength = 5};
struct ruleRightSideElement _term = {false, false, .symbol.nonTerminal = NT_Term};
struct ruleRightSideElement _moreTerms = {false, false, .symbol.nonTerminal = NT_MoreTerms};
RuleRightSideElement _rhs58[] = {&_term, &_moreTerms, };
struct rule _rule58 = {.lhs = NT_ArithmeticExpression, .rhs = _rhs58, .rhsLength = 2};
RuleRightSideElement _rhs59[] = {&_tk_op, &_arithmeticExpression, &_tk_cl, };
struct rule _rule59 = {.lhs = NT_ArithmeticExpression, .rhs = _rhs59, .rhsLength = 3};
RuleRightSideElement _rhs60[] = {&_var, };
struct rule _rule60 = {.lhs = NT_ArithmeticExpression, .rhs = _rhs60, .rhsLength = 1};
struct ruleRightSideElement _lowPrecedenceOperator = {false, false, .symbol.nonTerminal = NT_LowPrecedenceOperator};
RuleRightSideElement _rhs61[] = {&_lowPrecedenceOperator, &_term, &_moreTerms, };
struct rule _rule61 = {.lhs = NT_MoreTerms, .rhs = _rhs61, .rhsLength = 3};
RuleRightSideElement _rhs62[] = {&_eps, };
struct rule _rule62 = {.lhs = NT_MoreTerms, .rhs = _rhs62, .rhsLength = 1};
struct ruleRightSideElement _factor = {false, false, .symbol.nonTerminal = NT_Factor};
struct ruleRightSideElement _moreFactors = {false, false, .symbol.nonTerminal = NT_MoreFactors};
RuleRightSideElement _rhs63[] = {&_factor, &_moreFactors, };
struct rule _rule63 = {.lhs = NT_Term, .rhs = _rhs63, .rhsLength = 2};
struct ruleRightSideElement _highPrecedenceOperator = {false, false, .symbol.nonTerminal = NT_HighPrecedenceOperator};
RuleRightSideElement _rhs64[] = {&_highPrecedenceOperator, &_factor, &_moreFactors, };
struct rule _rule64 = {.lhs = NT_MoreFactors, .rhs = _rhs64, .rhsLength = 3};
RuleRightSideElement _rhs65[] = {&_eps, };
struct rule _rule65 = {.lhs = NT_MoreFactors, .rhs = _rhs65, .rhsLength = 1};
RuleRightSideElement _rhs66[] = {&_tk_op, &_arithmeticExpression, &_tk_cl, };
struct rule _rule66 = {.lhs = NT_Factor, .rhs = _rhs66, .rhsLength = 3};
RuleRightSideElement _rhs67[] = {&_var, };
struct rule _rule67 = {.lhs = NT_Factor, .rhs = _rhs67, .rhsLength = 1};
struct ruleRightSideElement _tk_mul = {false, true, .symbol.terminal = TK_MUL};
RuleRightSideElement _rhs68[] = {&_tk_mul, };
struct rule _rule68 = {.lhs = NT_HighPrecedenceOperator, .rhs = _rhs68, .rhsLength = 1};
struct ruleRightSideElement _tk_div = {false, true, .symbol.terminal = TK_DIV};
RuleRightSideElement _rhs69[] = {&_tk_div, };
struct rule _rule69 = {.lhs = NT_HighPrecedenceOperator, .rhs = _rhs69, .rhsLength = 1};
struct ruleRightSideElement _tk_plus = {false, true, .symbol.terminal = TK_PLUS};
RuleRightSideElement _rhs70[] = {&_tk_plus, };
struct rule _rule70 = {.lhs = NT_LowPrecedenceOperator, .rhs = _rhs70, .rhsLength = 1};
struct ruleRightSideElement _tk_minus = {false, true, .symbol.terminal = TK_MINUS};
RuleRightSideElement _rhs71[] = {&_tk_minus, };
struct rule _rule71 = {.lhs = NT_LowPrecedenceOperator, .rhs = _rhs71, .rhsLength = 1};
struct ruleRightSideElement _logicalOp = {false, false, .symbol.nonTerminal = NT_LogicalOp};
RuleRightSideElement _rhs72[] = {&_tk_op, &_booleanExpression, &_tk_cl, &_logicalOp, &_tk_op, &_booleanExpression, &_tk_cl, };
struct rule _rule72 = {.lhs = NT_BooleanExpression, .rhs = _rhs72, .rhsLength = 7};
struct ruleRightSideElement _relationalOp = {false, false, .symbol.nonTerminal = NT_RelationalOp};
RuleRightSideElement _rhs73[] = {&_var, &_relationalOp, &_var, };
struct rule _rule73 = {.lhs = NT_BooleanExpression, .rhs = _rhs73, .rhsLength = 3};
struct ruleRightSideElement _tk_not = {false, true, .symbol.terminal = TK_NOT};
RuleRightSideElement _rhs74[] = {&_tk_not, &_tk_op, &_booleanExpression, &_tk_cl, };
struct rule _rule74 = {.lhs = NT_BooleanExpression, .rhs = _rhs74, .rhsLength = 4};
struct ruleRightSideElement _tk_num = {false, true, .symbol.terminal = TK_NUM};
RuleRightSideElement _rhs75[] = {&_tk_num, };
struct rule _rule75 = {.lhs = NT_Var, .rhs = _rhs75, .rhsLength = 1};
struct ruleRightSideElement _tk_rnum = {false, true, .symbol.terminal = TK_RNUM};
RuleRightSideElement _rhs76[] = {&_tk_rnum, };
struct rule _rule76 = {.lhs = NT_Var, .rhs = _rhs76, .rhsLength = 1};
RuleRightSideElement _rhs77[] = {&_singleOrRecId, };
struct rule _rule77 = {.lhs = NT_Var, .rhs = _rhs77, .rhsLength = 1};
struct ruleRightSideElement _tk_and = {false, true, .symbol.terminal = TK_AND};
RuleRightSideElement _rhs78[] = {&_tk_and, };
struct rule _rule78 = {.lhs = NT_LogicalOp, .rhs = _rhs78, .rhsLength = 1};
struct ruleRightSideElement _tk_or = {false, true, .symbol.terminal = TK_OR};
RuleRightSideElement _rhs79[] = {&_tk_or, };
struct rule _rule79 = {.lhs = NT_LogicalOp, .rhs = _rhs79, .rhsLength = 1};
struct ruleRightSideElement _tk_lt = {false, true, .symbol.terminal = TK_LT};
RuleRightSideElement _rhs80[] = {&_tk_lt, };
struct rule _rule80 = {.lhs = NT_RelationalOp, .rhs = _rhs80, .rhsLength = 1};
struct ruleRightSideElement _tk_le = {false, true, .symbol.terminal = TK_LE};
RuleRightSideElement _rhs81[] = {&_tk_le, };
struct rule _rule81 = {.lhs = NT_RelationalOp, .rhs = _rhs81, .rhsLength = 1};
struct ruleRightSideElement _tk_eq = {false, true, .symbol.terminal = TK_EQ};
RuleRightSideElement _rhs82[] = {&_tk_eq, };
struct rule _rule82 = {.lhs = NT_RelationalOp, .rhs = _rhs82, .rhsLength = 1};
struct ruleRightSideElement _tk_gt = {false, true, .symbol.terminal = TK_GT};
RuleRightSideElement _rhs83[] = {&_tk_gt, };
struct rule _rule83 = {.lhs = NT_RelationalOp, .rhs = _rhs83, .rhsLength = 1};
struct ruleRightSideElement _tk_ge = {false, true, .symbol.terminal = TK_GE};
RuleRightSideElement _rhs84[] = {&_tk_ge, };
struct rule _rule84 = {.lhs = NT_RelationalOp, .rhs = _rhs84, .rhsLength = 1};
struct ruleRightSideElement _tk_ne = {false, true, .symbol.terminal = TK_NE};
RuleRightSideElement _rhs85[] = {&_tk_ne, };
struct rule _rule85 = {.lhs = NT_RelationalOp, .rhs = _rhs85, .rhsLength = 1};
struct ruleRightSideElement _tk_return = {false, true, .symbol.terminal = TK_RETURN};
struct ruleRightSideElement _optionalReturn = {false, false, .symbol.nonTerminal = NT_OptionalReturn};
RuleRightSideElement _rhs86[] = {&_tk_return, &_optionalReturn, &_tk_sem, };
struct rule _rule86 = {.lhs = NT_ReturnStmt, .rhs = _rhs86, .rhsLength = 3};
RuleRightSideElement _rhs87[] = {&_tk_sql, &_idList, &_tk_sqr, };
struct rule _rule87 = {.lhs = NT_OptionalReturn, .rhs = _rhs87, .rhsLength = 3};
RuleRightSideElement _rhs88[] = {&_eps, };
struct rule _rule88 = {.lhs = NT_OptionalReturn, .rhs = _rhs88, .rhsLength = 1};
struct ruleRightSideElement _moreIds = {false, false, .symbol.nonTerminal = NT_MoreIds};
RuleRightSideElement _rhs89[] = {&_tk_id, &_moreIds, };
struct rule _rule89 = {.lhs = NT_IdList, .rhs = _rhs89, .rhsLength = 2};
RuleRightSideElement _rhs90[] = {&_tk_comma, &_idList, };
struct rule _rule90 = {.lhs = NT_MoreIds, .rhs = _rhs90, .rhsLength = 2};
RuleRightSideElement _rhs91[] = {&_eps, };
struct rule _rule91 = {.lhs = NT_MoreIds, .rhs = _rhs91, .rhsLength = 1};
struct ruleRightSideElement _tk_definetype = {false, true, .symbol.terminal = TK_DEFINETYPE};
struct ruleRightSideElement _A = {false, false, .symbol.nonTerminal = NT_A};
struct ruleRightSideElement _tk_as = {false, true, .symbol.terminal = TK_AS};
RuleRightSideElement _rhs92[] = {&_tk_definetype, &_A, &_tk_ruid, &_tk_as, &_tk_ruid, };
struct rule _rule92 = {.lhs = NT_DefinetypeStmt, .rhs = _rhs92, .rhsLength = 5};
RuleRightSideElement _rhs93[] = {&_tk_record, };
struct rule _rule93 = {.lhs = NT_A, .rhs = _rhs93, .rhsLength = 1};
RuleRightSideElement _rhs94[] = {&_tk_union, };
struct rule _rule94 = {.lhs = NT_A, .rhs = _rhs94, .rhsLength = 1};

Rule _grammarRules[] = {&_rule0, &_rule1, &_rule2, &_rule3, &_rule4, &_rule5, &_rule6, &_rule7, &_rule8, &_rule9, &_rule10, &_rule11, &_rule12, &_rule13, &_rule14, &_rule15, &_rule16, &_rule17, &_rule18, &_rule19, &_rule20, &_rule21, &_rule22, &_rule23, &_rule24, &_rule25, &_rule26, &_rule27, &_rule28, &_rule29, &_rule30, &_rule31, &_rule32, &_rule33, &_rule34, &_rule35, &_rule36, &_rule37, &_rule38, &_rule39, &_rule40, &_rule41, &_rule42, &_rule43, &_rule44, &_rule45, &_rule46, &_rule47, &_rule48, &_rule49, &_rule50, &_rule51, &_rule52, &_rule53, &_rule54, &_rule55, &_rule56, &_rule57, &_rule58, &_rule59, &_rule60, &_rule61, &_rule62, &_rule63, &_rule64, &_rule65, &_rule66, &_rule67, &_rule68, &_rule69, &_rule70, &_rule71, &_rule72, &_rule73, &_rule74, &_rule75, &_rule76, &_rule77, &_rule78, &_rule79, &_rule80, &_rule81, &_rule82, &_rule83, &_rule84, &_rule85, &_rule86, &_rule87, &_rule88, &_rule89, &_rule90, &_rule91, &_rule92, &_rule93, &_rule94, };
struct grammar languageGrammar = {NT_Program, 95, _grammarRules};
#define NUM_NON_TERMINALS 107
#define NUM_RULES 95
#endif
