name: C/C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Check GCC version
      run: gcc-11 --version
    - name: make
      run: make stage1exe CC=gcc-11
    - uses: actions/upload-artifact@v4
      with:
        name: stage1exe-build
        path: ./stage1exe
        if-no-files-found: error
        overwrite: true
